version: '3.6'
services:
  ansible:
    image: ansible
    build:
      context: docker/
    volumes:
      - ./:/playbook
      - ./etc/ansible:/etc/ansible
      - ~/.ssh:/ssh:ro
    entrypoint: docker/entrypoint.sh
    command: sh
