- apt:
    name: '{{ item }}'
    install_recommends: no
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-pip
    - python-setuptools

- apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'

- apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- apt:
    name: 'docker-ce'
    update_cache: yes
    install_recommends: no

- pip:
    name: '{{ item }}'
  with_items:
    - docker-compose
